name: Heroku Buildpack with cnb-shim

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup pack CLI
        uses: buildpacks/github-actions/setup-pack@v4.5.1
      - name: Build
        id: build
        run: |
          pack build scrob-web \
            --buildpack https://cnb-shim.herokuapp.com/v1/heroku/ruby \
            --builder heroku/buildpacks:20
