name: Heroku Buildpack with cnb-shim

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  builder:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup pack CLI
        uses: buildpacks/github-actions/setup-pack@v4.8.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      #- uses: satackey/action-docker-layer-caching@v0.0.11
      #  name: Docker Layer Caching

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          #password: ${{ secrets.CR_PAT }}

      - name: Build
        id: build
        run: |
          pack build scrob-web \
            --buildpack https://cnb-shim.herokuapp.com/v1/heroku/ruby \
            --builder heroku/buildpacks:20 \
            --tag ghcr.io/kingdonb/scrob-web:${GITHUB_SHA::7} \
            --cache-image ghcr.io/kingdonb/scrob-web:buildcache \
            --publish

      # - name: Push
      #   id: push
      #   run: |
      #     docker push ghcr.io/kingdonb/scrob-web:${GITHUB_SHA::7}

