name: Kuby build and push manifests
on:
  push:
    branches:
      - main
      - staging

jobs:
  builder:
    name: Image Builder
    runs-on: self-hosted
    env:
      RUBY_VERSION: 3.1.3

    steps:
    - uses: actions/checkout@v2

    - name: Login to Harbor (img.hephy.pro)
      uses: docker/login-action@v1
      with:
        registry: img.hephy.pro
        username: ${{ secrets.HARBOR_BOT_USER }}
        password: ${{ secrets.HARBOR_BOT_PASSWORD }}

  # prebundler is: github.com/kingdonb/prebundler
  # (forked from github.com/camertron/prebundler)
    - name: Pre-cache dependencies
      run: rvm ${{ env.RUBY_VERSION }} do prebundle install
      env:
        MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
        MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    - name: Verify dependencies
      run: rvm ${{ env.RUBY_VERSION }} do bundle check

    - name: Set time zone to UTC properly
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: UTC

  # Build and push at once to allow "app" and "assets" to build as separate but
  # dependently (quirk of using docker buildx, if not then you can omit --push)
    - name: Kuby build/push app image
      run: rvm ${{ env.RUBY_VERSION }} do bundle exec kuby -e development build --only app --
        --build-arg=MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}
        --build-arg=MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}
        --push
        # && rvm ${{ env.RUBY_VERSION }} do bundle exec kuby -e production push
      env:
        # DOCKER_USERNAME: ${{ secrets.HARBOR_BOT_USER }}
        # DOCKER_PASSWORD: ${{ secrets.HARBOR_BOT_PASSWORD }}
        HARBOR_BOT_USER: ${{ secrets.HARBOR_BOT_USER }}
        HARBOR_BOT_PASSWORD: ${{ secrets.HARBOR_BOT_PASSWORD }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    - name: Kuby build/push assets image
      run: rvm ${{ env.RUBY_VERSION }} do bundle exec kuby -e development build --only assets --
        --build-arg=MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}
        --build-arg=MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}
        --push
      env:
        HARBOR_BOT_USER: ${{ secrets.HARBOR_BOT_USER }}
        HARBOR_BOT_PASSWORD: ${{ secrets.HARBOR_BOT_PASSWORD }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

#jobs:
  manifests:
    name: Manifests Builder
    runs-on: self-hosted
    needs: builder
    env:
      RUBY_VERSION: 3.1.3

    steps:
      - name: Prepare
        id: prep
        run: |
          VERSION=${GITHUB_SHA::8}
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=VERSION::${VERSION}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run manifest builder
        run: rvm ${{ env.RUBY_VERSION }} do ./builder.sh
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'manifests'
          branch: ${{ steps.extract_branch.outputs.branch }}
          message: "[ci skip] run kuby resources (builder.sh)"
          signoff: true
