name: Build kuby manifests
on:
  push:
    # tags: ['release/*']
    branches: ['main']

jobs:
  run:
    name: kuby manifests
    runs-on: self-hosted
    env:
      RUBY_VERSION: 3.0.3

    steps:
      - name: Prepare
        id: prep
        run: |
          VERSION=${GITHUB_SHA::8}
          # if [[ $GITHUB_REF == refs/tags/release/* ]]; then
          #   VERSION=${GITHUB_REF/refs\/tags\/release\//}
          # fi
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=VERSION::${VERSION}          

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Prepare target branch
        run: rvm ${{ env.RUBY_VERSION }} do ./builder.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'manifests'
          branch: main
          message: "[ci skip] run kuby resources (builder.sh)"
          signoff: true
